In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\home\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.salary_year_avg

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [5]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [16]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary * 1.05

df_salary['projected_salary'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg', 'projected_salary']].head(10)

     salary_year_avg  projected_salary
28          109500.0          114975.0
77          140000.0          147000.0
92          120000.0          126000.0
100         228222.0          239633.1
109          89000.0           93450.0
116         114000.0          119700.0
146         129500.0          135975.0
180          90250.0           94762.5
212         157500.0          165375.0
257         103128.0          108284.4

In [17]:
df_salary['projected_salary'] = df_salary['salary_year_avg'].apply(lambda x: x * 1.05)

df_salary[['salary_year_avg', 'projected_salary']].head(10)

     salary_year_avg  projected_salary
28          109500.0          114975.0
77          140000.0          147000.0
92          120000.0          126000.0
100         228222.0          239633.1
109          89000.0           93450.0
116         114000.0          119700.0
146         129500.0          135975.0
180          90250.0           94762.5
212         157500.0          165375.0
257         103128.0          108284.4

In [18]:
df.job_skills

0                                                       NaN
1         ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2         ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3         ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4         ['bash', 'python', 'oracle', 'aws', 'ansible',...
                                ...
785736    ['bash', 'python', 'perl', 'linux', 'unix', 'k...
785737                       ['sas', 'sas', 'sql', 'excel']
785738                              ['powerpoint', 'excel']
785739    ['python', 'go', 'nosql', 'sql', 'mongo', 'she...
785740                                      ['aws', 'flow']
Name: job_skills, Length: 785741, dtype: str

In [20]:
type(df['job_skills'][0])

float

In [22]:
print(df['job_skills'].head())
print(type(df['job_skills'][0]))

0                                                  NaN
1    ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2    ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3    ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4    ['bash', 'python', 'oracle', 'aws', 'ansible',...
Name: job_skills, dtype: str
<class 'float'>

In [23]:
import ast

df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else []
)

In [24]:
print(df['job_skills'][0])
print(type(df['job_skills'][0]))

[]
<class 'list'>

In [26]:
df['job_skills'][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [28]:
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return  1.03 * row['salary_year_avg']

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short' , 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

In [33]:
df_salary['salary_year_inflated'] = df_salary.apply(
    lambda row: 1.05 * row['salary_year_avg']
    if "Senior" in row['job_title_short']
    else 1.03 * row['salary_year_avg'],
    axis=1
)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]