In [31]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [32]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [33]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
167820,Data Scientist,Data Scientist-Junior,"Atlanta, GA",via BeBee,Full-time,False,Georgia,2023-12-07 16:04:16,False,False,United States,NaN,NaN,NaN,"Home Depot Management Company, LLC","['python', 'sql', 'bigquery', 'tableau']","{'analyst_tools': ['tableau'], 'cloud': ['bigq..."
165822,Senior Data Analyst,Senior Data Analyst,"Charlotte, NC",via Trabajo.org,Full-time,False,Georgia,2023-04-02 15:25:52,True,False,United States,NaN,NaN,NaN,Innova Solutions,NaN,NaN
346862,Senior Data Analyst,HR Technology Analyst (AC095),"Atlanta, GA",via ZipRecruiter,Contractor,False,Georgia,2023-06-21 23:52:48,True,False,United States,NaN,NaN,NaN,Primus Software Corporation,NaN,NaN
331092,Data Analyst,Data Analyst-ihp Nigeria-bagudo,Nigeria,via Emprego.pt,Full-time,False,Nigeria,2023-02-01 23:53:08,False,False,Nigeria,NaN,NaN,NaN,"Palladium Group, Inc.","['c', 'word', 'excel']","{'analyst_tools': ['word', 'excel'], 'programm..."
318548,Data Analyst,Institutional Research Data Analyst,"Durant, OK",via LinkedIn,Full-time,False,"Texas, United States",2023-02-11 17:02:51,False,False,United States,NaN,NaN,NaN,Southeastern Oklahoma State University,['sql'],{'programming': ['sql']}

In [ ]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [35]:
df_altered = df_original

In [36]:
df_altered.loc[0:10 ,'salary_year_avg']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
Name: salary_year_avg, dtype: float64

In [37]:
median_salary = df_altered['salary_year_avg'].median()

median_salary

np.float64(115000.0)

In [40]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

In [41]:
df_altered.loc[0:5 ,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [42]:
df_original.loc[0:5 ,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [43]:
print(f"ID of the original DataFrame: {id(df_original)}")
print(f"ID of the altered DataFrame: {id(df_altered)}")
print(id(df_original) == id(df_altered))

ID of the original DataFrame: 2299662747920
ID of the altered DataFrame: 2299662747920
True

# Copy()

In [49]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [50]:
df_altered = df_original.copy()

In [51]:
median_salary = df_altered['salary_year_avg'].median()

median_salary

np.float64(115000.0)

In [52]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[0:5 ,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [53]:
df_original.loc[0:5 ,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [55]:
print(f"ID of the original DataFrame: {id(df_original)}")
print(f"ID of the altered DataFrame: {id(df_altered)}")
print(id(df_original) == id(df_altered))

ID of the original DataFrame: 2299546328656
ID of the altered DataFrame: 2299662747920
False